<p><img src="images/img_bigenvelope.gif" alt="Logo" width="120"
height="88" align="left" border="0">This is a new installation of <a
href="http://www.kmmail.org/">kmMail</a>.  kmMail is a web-based mail
reader, written in PHP and based on the core functionality of <a
href="http://www.keftamail.com/">Keftamail</a>.  It focuses on speed, ease
of use, and MIME compliance.  kmMail is not a fully featured client, but a
framework for adding into existing functionality.  However, kmMail is
complete enough that it can be used standalone with no problem.</p>

<p>To start using kmMail, select one of the links on the top toolbar.  If
you go to an area that requires your username and password, you will be
prompted.  Be sure to type your information in carefully, as most likely
your username and password are case sensitive.  If your username and/or
password is not accepted, try again, or click the "cancel" button for a
little more information on what went wrong.</p>

<p>By the way, this text can be changed by the system administrator to
provide a more friendly greeting.  The HTML is in include/welcome.inc.</p>

<p>Good luck and thank you for using kmMail!</p>
