<?
// @(#) $Id: settings.inc,v 1.24 2001/10/01 06:31:49 ryanf Exp $

// This file contains defaults only.  Do not edit this file.
// Instead, edit config.inc.php

$old_error_reporting = error_reporting();
error_reporting(0);
include_once('include/config.inc.php');
error_reporting($old_error_reporting);

$config = array(
  'version' => '2.0',
  'build' => 'Wed Nov 21 15:51:06 PST 2001'
);

$profiles_defaults = array(
  'host' => $HTTP_HOST,
  'imap_host' => '127.0.0.1',
  'imap_port' => 143,
  'imap_mailpath' => 'mail/',
  'imap_mainbox' => 'INBOX',
  'display_folders' => 1,
  'use_sentbox' => 1,
  'imap_sentbox' => 'sent-mail',
  'use_passwd' => 1,
  'passwd_map' => array(
    'juser' => 'Joe User'
  ),
  'title' => 'kmMail',
  'mailbox_page_size' => 30,
  'send_udp_stat_packet' => 1,
  'use_virtusertable' => 0,
  'virtusertable_file' => '/etc/mail/virtusertable',
  'use_download_disclaimer' => 1,
  'download_disclaimer_text' => 'Warning! If you do not know who sent you this email, do not download the attached file. It could contain a computer virus that may compromise your system or contain questionable graphics.\n\nDo you wish to download this file?',
  'use_expunge_disclaimer' => 1,
  'expunge_disclaimer_text' => 'Warning! Are you sure you want to remove all deleted messages in all mailboxes?  There is no way to undo this action.',
  'west_of_utc' => 1,
  'imap_timezone_offset' => 0,

  'addressbook_folder' => 'addressbook',


  'the' => 'end'
);

if($profiles) {
  $akeys = array_keys($profiles);
  for($i = 0; $i < count($akeys); $i++) {
    $profile_name = $akeys[$i];
    $profiles[$profile_name] = array_merge($profiles_defaults, $profiles[$profile_name]);
  }
} else {
  $profiles = array(
    $profiles_defaults['host'] => $profiles_defaults
  );
}

?>
